{% set name = "csvinsight" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/csvinsight-{{ version }}.tar.gz
  sha256: 7f2553a4e6d3e2df71c5fada6c28eea4a3d78cd545957e96e7fc71fbbc88299f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - csvi = csvinsight.cli:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - plumbum
    - pyyaml
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - csvinsight
  # plumbum 1.7.2 requires pywin32, which is not installed.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/ProfoundNetworks/csvinsight
  summary: Fast & simple summary for large CSV files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
